---
destination : _site
lsi         : false
highlighter : pygments
permalink   : pretty
markdown    : kramdown
include     : [".htaccess"]
exclude	    : ["rsync-site.sh", ".git", ".gitignore", "Gemfile", "Gemfile.lock", "script", "vendor"]
url         : "http://kyle.niemeyer.com"

author:
    name : Kyle Niemeyer
    email : kyle.niemeyer@gmail.com
    github : kyleniemeyer
    twitter : kyle_niemeyer

kramdown:
    parse_block_html: true
